import { chromium } from 'playwright';
import { serve } from './serve.mjs';
const { server, url } = await serve(0);
const b = await chromium.launch({ args: ['--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-webgl','--disable-gpu-sandbox','--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 960, height: 540 } });
const logs=[]; const IG=/GL Driver|ReadPixels|Slow read-back|SwiftShader|Context Lost/i;
p.on('console',m=>{const t=m.text(); if((m.type()==='error'||m.type()==='warning')&&!IG.test(t))logs.push(t)});
p.on('pageerror',e=>logs.push('[pageerror] '+e.message));
await p.goto(url, { waitUntil:'load', timeout:90000 });
await p.waitForFunction(()=>window.__GAME?.ready===true,null,{timeout:150000});
await p.waitForTimeout(3000);
const before = await p.evaluate(()=>({ wpn: window.__GAME.weapon?.viewmodelScene?.visible, enemies: window.__GAME.registry.enemies.length }));
await p.evaluate(()=>window.__GAME.thirdperson.setEnabled(true));
await p.waitForTimeout(2200);
const during = await p.evaluate(()=>({ wpn: window.__GAME.weapon?.viewmodelScene?.visible, on: window.__GAME.thirdperson.on }));
await p.screenshot({ path:'shots/bs-thirdperson.png', timeout:180000 });
await p.evaluate(()=>window.__GAME.thirdperson.setEnabled(false));
await p.waitForTimeout(1200);
const after = await p.evaluate(()=>({ wpn: window.__GAME.weapon?.viewmodelScene?.visible }));
console.log('적:', before.enemies, '| 무기 1인칭:', before.wpn, '→ 3인칭:', during.wpn, '→ 복귀:', after.wpn);
console.log('콘솔 이슈:', logs.length); logs.slice(0,5).forEach(l=>console.log('  ',l));
await b.close(); server.close();